# Generated by Django 3.2.15 on 2022-09-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_day',
            field=models.CharField(choices=[('0', 'Tuesday'), ('1', 'Wednesday'), ('2', 'Thursday'), ('3', 'Friday'), ('4', 'Saturday')], default='0', max_length=10),
        ),
    ]
