# Generated by Django 3.2.15 on 2022-09-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_name',
            field=models.TextField(blank=True, max_length=50, verbose_name='Guest'),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_phone',
            field=models.TextField(blank=True, max_length=50, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_day',
            field=models.CharField(choices=[('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], default='Tue', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.CharField(choices=[('17.00-18.30', '17.00-18.30'), ('18.30-20.00', '18.30-20.00'), ('20.00-21.30', '20.00-21.30')], default='17.00-18.30', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_guests',
            field=models.CharField(choices=[('One guest', 'One guest'), ('Two guests', 'Two guests'), ('Three guests', 'Three guests'), ('Four guests', 'Four guests'), ('Five guests', 'Five guests'), ('Six guests', 'Six guests'), ('Seven guests', 'Seven guests'), ('Eight guests', 'Eight guests')], default='Two guests', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('guest_email', 'booking_day', 'booking_time')},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest',
        ),
    ]
